### ISSUE TITLE
Stoke gov uk not working

### ISSUE THREAD

**Issue by Doghousestaffs** [mampfes/hacs_waste_collection_schedule#1364]
Getting the following error suddenly 

```
This error originated from a custom integration.

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 01:54:04 (1 occurrences)
Last logged: 01:54:04

fetch failed for source Stoke-on-Trent: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/stoke_gov_uk.py", line 49, in fetch date = datetime.strptime(date_time, DATE_FORMAT).date() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime raise ValueError("time data %r does not match format %r" % ValueError: time data '13/10/2023' does not match format '%d/%m/%Y %H:%M:%S'
```

**Comment by 5ila5** [comment]
looks like the website returns a date 13/10/2023 without a timestamp. Our test cases all return a date with time. in #1368 i Just removed the timestamp and only parse the date this should fix this issue. 

fix will be part of release 1.44.0 or is available now as master (git) version

**Comment by Doghousestaffs** [comment]
Issue still persisting, I’ve added the new .py file but sensors still showing unknown after ha restart

**Comment by 5ila5** [comment]
Could you please provide the new log or is it exactly the same message?

**Comment by Doghousestaffs** [comment]
No error at all that I can see except all my sensors are in unknown stare
________________________________

**Comment by 5ila5** [comment]
The source returns valid data for the uprns `3455011391` and `3455011383` but your described behaviour sounds like a configuration issue. Is your calendar populated with events? whats your sensor configuration.

To be save please try one of the example upnrs (don't forget to restart Homeassistant).

**Comment by Doghousestaffs** [comment]
waste_collection_schedule:
  sources:
    - name: stoke_gov_uk
      args:
        uprn: "3455011383
________________________________

**Comment by 5ila5** [comment]
types `EMPTY BINS RESIDUAL BIN` `EMPTY BINS ORG 240 STD` `Empty Bin REC 240 STD` are not provided by the source (with this UPRN). I only get `Empty Bin RESIDUAL BIN` and `Empty Bin MIXED REC 55 BOX` Your can see your collection event names in the Calendar Tab of Homeassistant

**Comment by Doghousestaffs** [comment]
That’s the issue then, the names have changed lol
________________________________

**Comment by Doghousestaffs** [comment]
Somethings still off, calendar showing both bins being collected together which doesn’t happen
________________________________

**Comment by Doghousestaffs** [comment]
________________________________

**Comment by Doghousestaffs** [comment]
Change the file back, not sure what they done but my uprn comes in as3455011390<https://www.stoke.gov.uk/jadu/custom/webserviceLookUps/BarTecWebServices_missed_bin_calendar.php?UPRN=%203455011390> and strangely that works now..with the old code 🤔

**Comment by Doghousestaffs** [comment]
Change the file back, not sure what they done but my uprn comes in as[3455011390](https://www.stoke.gov.uk/jadu/custom/webserviceLookUps/BarTecWebServices_missed_bin_calendar.php?UPRN=%203455011390) and strangely that works now..with the old code
