### ISSUE TITLE
[Bug]: Fetch error for rh_entsorgung_de

### ISSUE THREAD

**Issue by pasarn** [mampfes/hacs_waste_collection_schedule#1455]
### I Have A Problem With:

A specific source

### What's Your Problem

I get no data enymore.

This is the Error in the Logs:

fetch failed for source Rhein-Hunsrück Entsorgung (RHE): Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 340, in parts validate_token(name) File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 128, in validate_token raise ValueError(name) ValueError: <!DOCTYPE HTML> During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/rh_entsorgung_de.py", line 97, in fetch dates = self._ics.convert(r.text) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 330, in from_ical name, params, vals = line.parts() ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 352, in parts raise ValueError( ValueError: Content line could not be parsed into parts: '<!DOCTYPE HTML>': <!DOCTYPE HTML> 

### Source (if relevant)

rh_entsorgung_de

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
fixed by #1464 
fix is part of release 1.44.0

**Comment by pasarn** [comment]
Hi, unfortunately the problem is not fixed. (Version 1.45.0)

`2024-01-17 13:15:24.515 ERROR (SyncWorker_1) [waste_collection_schedule.source_shell] fetch failed for source Rhein-Hunsrück Entsorgung (RHE):
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 340, in parts
validate_token(name)
File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 128, in validate_token
raise ValueError(name)
ValueError: <!DOCTYPE HTML>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
entries = self._source.fetch()
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/rh_entsorgung_de.py", line 55, in fetch
entries = self.get_entries(now.year)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/rh_entsorgung_de.py", line 107, in get_entries
dates = self._ics.convert(r.text)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert
events: List[Any] = icalevents.events(
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events
found_events += parse_events(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, in parse_events
calendar = Calendar.from_ical(content)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 330, in from_ical
name, params, vals = line.parts()
^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 352, in parts
raise ValueError(
ValueError: Content line could not be parsed into parts: '<!DOCTYPE HTML>': <!DOCTYPE HTML>`
