### ISSUE TITLE
[Bug]: Bracknell Forest missing Collection Type

### ISSUE THREAD

**Issue by hobnob48** [mampfes/hacs_waste_collection_schedule#2982]
### I Have A Problem With:

A specific source

### What's Your Problem

My existing configuration has stopped displaying the number of days for General collection and now shows as unknown. Food and Recycling are working correctly.

Clicking through the new UI process to re-configure the integration, the "Type" list only shows Food and Recycling. Previously I believe this would have sown General aswell.

Settings used to re-add and verify:
Country: United Kingdom
Source:  Bracknell Forest Council (bracknell_forest_gov_uk)
Postcode: RG42 2HB
House Number: 44

Using the below in configuration.yaml also only shows the 2 types.

sensor:
 - platform: waste_collection_schedule
   name: .All

### Source (if relevant)

bracknell_forest_gov_uk

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by kevbev67** [comment]
I'm not much help but can confirm that its not working for me in Bracknell Forest either. Just Recycling and Food options

**Comment by 5ila5** [comment]
fixed in #3016

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by jbarrett-fmad** [comment]
I am still having problems with this, despite the updates.

Food and Recycling work fine, I can see General waste in the calendar, so the API issue has clearly been fixed, but the sensor.waste_collection_general state remains unknown.

![image](https://github.com/user-attachments/assets/d88068aa-91c2-4b5a-ab71-19a82b23915b)

![image](https://github.com/user-attachments/assets/ddf08756-9c23-47b8-8611-08bc554a089d)

I have updated by every method I know, including per 5ila5's instruction above, manually copying the latest master from GH to custom_components.

**Comment by 5ila5** [comment]
@jbarrett-fmad this sounds like a configuration issue of this sensor. Maybe they changed the name/typing of the general waste collection and your sensor does not pick it up anymore. If you use the GUI configuration, you can change the sensor configuration by clicking configure next to your WCS source. 

Make sure the name in the `types` configuration matches the spelling in your calendar

**Comment by cpressland** [comment]
You'll need to lower case the `w` on `Waste` in your `configuration.yaml`, for example:

```yaml
waste_collection_schedule:
  sources:
    - name: bracknell_forest_gov_uk
      args:
        post_code: "RG12 1AB"
        house_number: "123"

sensor:
  - platform: waste_collection_schedule
    name: waste_collection_food
    add_days_to: true
    types:
      - Food
  - platform: waste_collection_schedule
    name: waste_collection_recycling
    add_days_to: true
    types:
      - Recycling
  - platform: waste_collection_schedule
    name: waste_collection_garden
    add_days_to: true
    types:
      - Garden
  - platform: waste_collection_schedule
    name: waste_collection_general
    add_days_to: true
    types:
      - General waste
```

I'm not sure why Bracknell Council decided to lower case the word waste.

**Comment by jbarrett-fmad** [comment]
Thanks @cpressland. I'm an idiot. I hadn't properly searched my configuration.yaml and the sensor statements were a couple of thousand lines from the sources section. Must be more thorough in future.
