### ISSUE TITLE
[Bug]: Not colecting data from warszawa19115.pl

### ISSUE THREAD

**Issue by Tomkee** [mampfes/hacs_waste_collection_schedule#3095]
### I Have A Problem With:

A specific source

### What's Your Problem

Not collecting data for addon.

I can get proper data from terminal by using terminal and 

curl -X GET "https://warszawa19115.pl/harmonogramy-wywozu-odpadow?p_p_id=portalCKMjunkschedules_WAR_portalCKMjunkschedulesportlet_INSTANCE_o5AIb2mimbRJ&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=ajaxResource&p_p_cacheability=cacheLevelPage&_portalCKMjunkschedules_WAR_portalCKMjunkschedulesportlet_INSTANCE_o5AIb2mimbRJ_addressPointId=xxxxxxx" -H "Accept: application/json"

I am not programer myself by tried to:
- Use Chat GPT to fix isue
- Recover old HA instalation with old configuration
- Downgrade to 2.0 Wast colection schedule addon
- Inserting street adress and geoid
- Changing city to MPGK Katowice and data is downloading normally

Nothing worked for me. 

### Source (if relevant)

warszawa19115.pl

### Logs

```Shell
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 12:39:55 AM (2 occurrences)
Last logged: 1:17:40 AM

fetch failed for source Warsaw: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/warszawa19115_pl.py", line 127, in fetch or len(calendar_result[0]["harmonogramy"]) <= 0 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: object of type 'NoneType' has no len()
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: warszawa19115_pl
      args:
        geolocation_id: xxxxxx
      customize:
        - type: Szkło
          alias: Szkło
        - type: Zielone
          alias: Zielone
        - type: Bio
          alias: Bio
        - type: Metale i tworzywa sztuczne
          alias: Metale i plastik
        - type: Papier
          alias: Papier
        - type: Odpady zmieszane
          alias: Odpady zmieszane
        - type: Odpady wielkogabarytowe
          alias: Odpady wielkogabarytowe
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by sbochnak** [comment]
Hey to all,
I have found the reason of the bug, only to find that the code is already corrected and submitted for couple of weeks, but the correction was not included in the latest version (2.4.0).

One needs to change "harmonogramy" with "harmonogramyZ" in fetch function of warszawa19115_pl.py file before the approved correction gets published.
Path to the file: custom_components/waste_collection_schedule/waste_collection_schedule/source/warszawa19115_pl.py

I have done it. It works, but after changing file I had to restart Home Assistant.

I attach my version of changes from line 123 to line 143 .

```
        _LOGGER.debug(f"Calendar response: {calendar_result!r}")
line 123:
        SCHEDULES = "harmonogramyZ"
        if (
            len(calendar_result) <= 0
            or SCHEDULES not in calendar_result[0]
            or len(calendar_result[0][SCHEDULES]) <= 0
        ):
            raise SourceParseError(
                f"Expected list of dates from calendar search, got empty or missing list (possibly no '{SCHEDULES}' entry found)"
            )

        entries = []

        for result in calendar_result:
            for entry in result[SCHEDULES]:
                if entry["data"]:
                    original_type = entry["frakcja"]["id_frakcja"]
                    waste_type = NAME_MAP.get(original_type, original_type)
                    waste_date = datetime.strptime(entry["data"], "%Y-%m-%d").date()
                    entries.append(Collection(waste_date, waste_type))`
line 143:
    return entries

**Comment by Tomkee** [comment]
Copying and changing warszawa19115_pl.py didn't fix my issue but the new update did. Thank you for the quick answer and quick fix. This is truly one of the greatest add-ons for HA. It's very important for me. Thx for your work.

**Comment by andrewt27** [comment]
Is anyone else having issues with this add-on? It stopped working after installing the latest HA 2025.2.4—it was working until yesterday.

### Logs

`Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 18 February 2025 at 19:31:39 (2 occurrences)
Last logged: 01:53:31

fetch failed for source Warsaw: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/warszawa19115_pl.py", line 101, in fetch self._geolocation_id = self.get_geolocation_id(self._street_address) ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/warszawa19115_pl.py", line 80, in get_geolocation_id raise SourceParseError( "Expected list of locations from address search, got empty or missing list" ) waste_collection_schedule.source.warszawa19115_pl.SourceParseError: Expected list of locations from address search, got empty or missing list`

### Testing options

When changing city to Wroclaw - it works, Warsaw do not

**Comment by sbochnak** [comment]
Unfortunately, yes - I do have problem with this add-on.
I am getting exactly the same error.
What I determined, add-on moved from yaml config to integration with HA UI, where one needs to define everything now. 
I went this path, trying to recreate the config I had in YAML, but it still does not seem to work. :(
