### ISSUE TITLE
[Bug]: Invalid Response - London Borough of Merton (UK)

### ISSUE THREAD

**Issue by bazzar1206** [mampfes/hacs_waste_collection_schedule#3333]
### I Have A Problem With:

A specific source

### What's Your Problem

UK - London Borough of Merton

Previously correct entity worked but then showed "unavailable". When trying to set up the source, it states "The source returned an invalid response: "time data 'Friday 3 January 2025' does not match format '%d %B %Y'". Please check the provided arguments and try again."

The source previously provided data but is no longer working. Must have changed within the last 1-2 months.

### Source (if relevant)

merton_gov_uk

### Logs

```Shell
No relevant log
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by dt215git** [comment]
Possibly fixed by recent PR #3317

**Comment by halcycon** [comment]
I am experiencing the same issue. I have just manually cloned the repo following PR #3317 to replace the version that was installed via HACS (as the release is older), and am still experiencing the same error. HtH

**Comment by dt215git** [comment]
![image](https://github.com/user-attachments/assets/4f1bd57c-418a-4457-a59f-9aeb4b1b41ec)
Test cases worked yesterday, and now one of them fails - Looks like they're being inconsistent in the date formats.
I've updated the script to try and handle both formats, but as mentioned in the PR linked above, the merton_gov_uk source is using their old api, so it's anyone's guess how long it'll remain functional.

Details on using their new api can be found [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/merton_gov_uk.md)

**Comment by halcycon** [comment]
Appreciate the rapid response, and equally an issue likely isn't the right place to report this - but I've tried to move to the new API following that link, and while I can see some providers listed with (ics) following them, I don't see a merton_gov_uk (new) (or similar). I've tried to configure using another region but using my generated .ics URL, but I ran into "an unknown error occurred" - is there a generic ICS provider or do I need to write one?

**Comment by dt215git** [comment]
Oops, my bad - the change was made to the master branch and will be included in the next release.
You can pull down the master branch (and all changes since the last release like this:

![image](https://github.com/user-attachments/assets/6ba2d1d7-96d9-4ee3-9863-a68b6d67ca75)

Once you've restarted HA, you should be able to see the new Merton option when using the GUI to set up a new source.
Select the UK, and then search for "merton":

![image](https://github.com/user-attachments/assets/69d5ea6d-bf92-4387-8b89-26b3034fd212)

Pick the ics option, and then follow the previously mention instructions on how to find the url to copy into the config dialog.

Using the test case url, i get this:
![image](https://github.com/user-attachments/assets/752663f8-ca23-4211-a71e-a958b25d49e4)

**Comment by halcycon** [comment]
Thanks - I was going to edit my previous comment to say I was being an ID-Ten-T, and I had then seen the instruction during configuration of how to set up an ICS source, which I got working.

Thanks for the instrcutions on pulling down master, I had cloned the repo manually to get the most up-to-date content, but this is much neater!

I have tried the instructions to search for merton, and get the following: 
![image](https://github.com/user-attachments/assets/e498f8a1-9ca2-429e-aa48-79fb32df288e)

I can confirm I'm definitely on version 2dc7945, so this is very odd...

**Comment by 5ila5** [comment]
fixed in #3351

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
