### ISSUE TITLE
[Bug]: Swale Bourough Council (UK) Not Working

### ISSUE THREAD

**Issue by apmillen** [mampfes/hacs_waste_collection_schedule#3492]
### I Have A Problem With:

A specific source

### What's Your Problem

Tried to configure my council's waste schedule (Swale Bourough Council, United Kingdom) but is showing the following error:

The source returned an invalid response: "Could not find SBC-YBD_main section. Most likely html has changed". Please check the provided arguments and try again.

### Source (if relevant)

swale_gov_uk

### Logs

```Shell
no relevant logs
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by dt215git** [comment]
Looks like they've subtly changed their forms and the structure of the results page - the script needs updating.

**Comment by 5ila5** [comment]
fixed in  #3548 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by AKWillows** [comment]
Hi - I think this is still broken. I have version 2.6.0 but am still getting the same error 

<img width="572" alt="Image" src="https://github.com/user-attachments/assets/ccacc9b1-891b-4a51-ab3b-7a0f43649811" />

**Comment by dt215git** [comment]
2.6 was released on 8th Jan, the fix was merged on the 17th Jan, that would explain  you see the same message as the original post.

You can wait for the next release, or follow the note 5ila5 gave for pulling down the master/git version. The master/git version contains _all_ the merges since the last release.

Maybe this helps:

![Image](https://github.com/user-attachments/assets/50c50fdf-6245-45ce-8633-9658a3a4c5bf)

Test cases are pulling back results okay.
