### ISSUE TITLE
[Bug]: Recycle coach stopped working and throws error on trying to configure same source again

### ISSUE THREAD

**Issue by muzammilk** [mampfes/hacs_waste_collection_schedule#4310]
### I Have A Problem With:

The integration in general

### What's Your Problem

The sensors and calendar stopped working so I tried setting up again and now it throws an error while setting it up as new. The address which I am using was working till last week.

### Source (if relevant)

Recycle Coach (recyclecoach_com)

### Logs

```Shell
The source returned an invalid response: "HTTPSConnectionPool(host='pkg.my-waste.mobi', port=443): Max retries exceeded with url: /app_data_zone_schedules?project_id=590&district_id=DELR&zone_id=zone-z7778-z19169 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f306b1f8e10>: Failed to establish a new connection: [Errno -5] Name has no usable address'))". Please check the provided arguments and try again.
```

### Relevant Configuration

```YAML
Installation method Home Assistant OS
Core 2025.6.2
Supervisor 2025.06.1
Operating System 15.2
Frontend 20250531.3

Waste collection schedule 2.8.0

```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by gregprosser** [comment]
This has been failing for a few days for me - it looks like my logs say since June 20:

```
$ docker logs homeassistant |& grep 'fetch failed for source'
2025-06-20 01:54:24.247 ERROR (SyncWorker_10) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-20 01:54:42.152 ERROR (SyncWorker_15) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-20 11:29:47.075 ERROR (SyncWorker_0) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-20 11:29:47.086 ERROR (SyncWorker_6) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-21 01:12:19.494 ERROR (SyncWorker_7) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-21 01:13:39.440 ERROR (SyncWorker_13) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-22 01:11:07.597 ERROR (SyncWorker_3) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-22 01:33:21.470 ERROR (SyncWorker_32) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-23 01:31:09.478 ERROR (SyncWorker_30) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-23 01:51:11.486 ERROR (SyncWorker_14) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-24 01:07:37.511 ERROR (SyncWorker_25) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-24 01:08:45.442 ERROR (SyncWorker_0) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-25 01:32:10.473 ERROR (SyncWorker_31) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-25 01:41:17.421 ERROR (SyncWorker_12) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-25 11:20:59.475 ERROR (SyncWorker_14) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-25 11:21:03.677 ERROR (SyncWorker_12) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-26 01:02:02.650 ERROR (SyncWorker_6) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-26 01:16:57.455 ERROR (SyncWorker_26) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-26 01:49:16.635 ERROR (SyncWorker_8) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
2025-06-26 01:56:36.232 ERROR (SyncWorker_30) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Recycle Coach:
```

It appears the host referenced in the source `pkg.my-waste.mobi` doesn't exist in DNS anymore.  I'm pretty sure the other host in the source works...

**Comment by gregprosser** [comment]
I think #4317 should fix this - I ran the source tests but I ~~didn't get a chance to fully load it in HA -~~ if anyone else wanted to give it a shot that would be greatly appreciated.

Edit: I've now tested it and this makes the data come back for me!

**Comment by ldafogel** [comment]
I'm also missing data due to this.

**Comment by muzammilk** [comment]
Anyone was able to make it work? I still see the error with release 2.9.0.

**Comment by gregprosser** [comment]
> Anyone was able to make it work? I still see the error with release 2.9.0.

I have a PR open to fix this, but it hasn't been landed - so this is likely still going to be broken.  You can follow along in #4317.

If you're comfortable, you can get a fix by pulling that PR (or at least, test it to see if there's fixes required!)

**Comment by muzammilk** [comment]
> > Anyone was able to make it work? I still see the error with release 2.9.0.
> 
> I have a PR open to fix this, but it hasn't been landed - so this is likely still going to be broken. You can follow along in [#4317](https://github.com/mampfes/hacs_waste_collection_schedule/pull/4317).
> 
> If you're comfortable, you can get a fix by pulling that PR (or at least, test it to see if there's fixes required!)

After copying the recyclecoach_com.py file I was able to configure using the street address and the region prefix. Works for me.
Really appreciate all the work you’ve put into this. Thanks a lot!

**Comment by 5ila5** [comment]
fixed in  #4616 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA
