### ISSUE TITLE
[Bug]: 1COAST stopped working with 404 Client Error

### ISSUE THREAD

**Issue by jaromanda** [mampfes/hacs_waste_collection_schedule#4361]
### I Have A Problem With:

A specific source

### What's Your Problem

This stopped working some time in the last week, I originally thought it was the 2.9.0 upgrade, but same issue with the previous version.

Manually checking the website, I see there is a "captcha" when requesting bin night information, not sure if this is new, but the website does look different from the last time I used it 5 months ago

### Source (if relevant)

1coast_com_au

### Logs

```Shell
fetch failed for source 1Coast - Central Coast: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/1coast_com_au.py", line 81, in fetch return self._get_collections() ~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/1coast_com_au.py", line 126, in _get_collections r.raise_for_status() ~~~~~~~~~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1026, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://1coast.com.au/calendar/05072025/event_704946_05072025.ics During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/1coast_com_au.py", line 86, in fetch return self._get_collections() ~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/1coast_com_au.py", line 126, in _get_collections r.raise_for_status() ~~~~~~~~~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1026, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://1coast.com.au/calendar/05072025/event_704946_05072025.ics
fetch failed for source 1Coast - Central Coast: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/1coast_com_au.py", line 81, in fetch return self._get_collections() ~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/1coast_com_au.py", line 126, in _get_collections r.raise_for_status() ~~~~~~~~~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1026, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://1coast.com.au/calendar/06072025/event_704946_06072025.ics During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/1coast_com_au.py", line 86, in fetch return self._get_collections() ~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/1coast_com_au.py", line 126, in _get_collections r.raise_for_status() ~~~~~~~~~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1026, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://1coast.com.au/calendar/06072025/event_704946_06072025.ics
```

### Relevant Configuration

```YAML

```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by dt215git** [comment]
The script is downloading an ics file containing the collection dates, can you download that file from the website, or does that also fail? If it does fail, it's an issue with the website.

**Comment by jaromanda** [comment]
The URL does not exist, would not say the site has an issue, I think it has changed

**Comment by dt215git** [comment]
If you use the script's test case on the website you are given the following url for the ics file: https://1coast.com.au/calendar/07072025/event_711491_07072025.ics
If you click on their link, you get the 404 Page not found error.

For the same address, the script returns this url: https://1coast.com.au/calendar/07072025/event_711491_07072025.ics
They're the same, and the script also returns the 404 Page not found error.

I don' think the website has changed; I think it's broken, and the script is just replicating that broken behaviour.

You may be better off contacting them and asking  why their calendar download link doesn't work.

**Comment by jaromanda** [comment]
Apologies, I hadn't used the test case in that way, I just used as a test address in the integration.

I now see what you mean though.

I will try to contact council regarding this, but I've only ever had poor experience with getting any useful information from government bodies in Australia regarding API issues like this.

**Comment by smarthomejunkie** [comment]
I experience the same with afvalwijzer and Afvalstoffendienst in the Netherlands.

**Comment by dt215git** [comment]
@smarthomejunkie Probably best to open a new issue, there's no way an update to an Australian waste provider is going to fix an issue with the collection of Dutch bins 😆

**Comment by 5ila5** [comment]
fixed in  #4384 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

**Comment by MrHakisak** [comment]
> fixed in [#4384](https://github.com/mampfes/hacs_waste_collection_schedule/pull/4384)
> 
> This will be part of the next release or is available now as master (git) version
> 
> install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

Hello,
I am on 2.9.0 and this issue is still not fixed. Is there something else I have to do to get it working? I don't understand where I'm supposed to do the last part of your comment.
-Thank you

**Comment by jaromanda** [comment]
> Hello, I am on 2.9.0 and this issue is still not fixed.

2.9.0 was, coincidentally, released on the day I created this issue - note: the release had nothing to do with the issue, just a coincidence of when I created the issue - the actual issue is that 1Coast broke the calendar (.ics) link

My understanding is that the NEXT release will include the workaround - or you can follow the instructions to use the master (git) version using the Developer tools in Home Assistant

**Comment by MrHakisak** [comment]
> 2.9.0 was, coincidentally, released on the day I created this issue - note: the release had nothing to do with the issue, just a coincidence of when I created the issue - the actual issue is that 1Coast broke the calendar (.ics) link
> 
> My understanding is that the NEXT release will include the workaround - or you can follow the instructions to use the master (git) version using the Developer tools in Home Assistant

Thank you for the pointers, that seemed to fix it.
