### ISSUE TITLE
[Bug]: Bolton Council [UK]

### ISSUE THREAD

**Issue by darrencuk** [mampfes/hacs_waste_collection_schedule#4662]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi. 

Bolton council looks to have changed something. I’m not getting any results for collections. 

I’ve attached an error I’ve found whilst troubleshooting. 

<img width="1179" height="2556" alt="Image" src="https://github.com/user-attachments/assets/862cc304-52f0-4e3e-a41f-d269ce0f37ba" />

This is the url for the collections

https://www.bolton.gov.uk/next-bin-collection

Thanks for all the hard work. Very much appreciated!

### Source (if relevant)

https://www.bolton.gov.uk/

### Logs

```Shell

```

### Relevant Configuration

```YAML

```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by XargsUK** [comment]
I'll be doing a PR shortly to resolve this.

**Comment by 5ila5** [comment]
fixed in #4664 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

**Comment by darrencuk** [comment]
Hi 

Thanks for your help. I have tried the above but I am still getting the same error.

Darren.
