### ISSUE TITLE
[Bug]: Derby City Council - unavailable

### ISSUE THREAD

**Issue by Paul-G-M** [mampfes/hacs_waste_collection_schedule#4829]
### I Have A Problem With:

The integration in general

### What's Your Problem

Calendar feed for Derby City Council has been working faultlessly for many months. Noticed several days ago that no data was being fetched. Council website is working as normal & premises ID has not changed. I also tried using postcode & house number instead of premises ID. Still no calendar entries.
One thing I did notice was that the url of the council binday site is “secure.derby.gov.uk/binday/“ when you first enter the site but then gets an additional “BinDays” in the url when the premisesID is added, to
“secure.derby.gov.uk/binday/BinDays/<premisesID>”. I don’t know whether this is how it’s always been, but thought it worth a mention

### Source (if relevant)

derby_gov_uk

### Logs

```Shell
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 17 October 2025 at 17:59:04 (2 occurrences)
Last logged: 01:33:25

fetch failed for source Derby City Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/derby_gov_uk.py", line 81, in fetch self._premises_id = params["PremisesId"].pop() ~~~~~~^^^^^^^^^^^^^^ KeyError: 'PremisesId'
```

### Relevant Configuration

```YAML

```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [ ] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Paul-G-M** [comment]
Apologies, missed the fact that another bug was raised for this council

**Comment by Azelphur** [comment]
@Paul-G-M I believe you as the issue creator can close this. This one is the newer one so it makes sense to close this one. Any discussion can continue in #4828

**Comment by Paul-G-M** [comment]
Thanks @Azelphur, this fixed it for me too. Much appreciated.

**Comment by 5ila5** [comment]
Fixed by #4824 

If you used Post code + house number lookup, you need to reconfigure your source

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA
Do "update" of WCS until the next release, as pressing the update button performs a "downgrade" to the latest release version

**Comment by spuddyspudspud** [comment]
> Fixed by [#4824](https://github.com/mampfes/hacs_waste_collection_schedule/pull/4824)
> 
> If you used Post code + house number lookup, you need to reconfigure your source
> 
> This will be part of the next release or is available now as master (git) version
> 
> install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA Do "update" of WCS until the next release, as pressing the update button performs a "downgrade" to the latest release version

I've tried all this but still cant make it work? 

I get the following error:

The integration could not be loaded, try to restart Home Assistant.

Any tips please?
