### ISSUE TITLE
[Bug]: Auckland Council No longer working

### ISSUE THREAD

**Issue by PHamiltonNZ** [mampfes/hacs_waste_collection_schedule#4841]
### I Have A Problem With:

A specific source

### What's Your Problem

Auckland Council collection dates are no longer working from what i can tell

### Logs

```Shell

```

### Relevant Configuration

```YAML

```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Alfiegerner** [comment]
Fixed in PR #4842

**Comment by azza5069** [comment]
Hi, just confirming that I’m still experiencing this issue on the latest versions. My sensors show as “unknown”.

Versions:
• Home Assistant Core: 2025.10.3
• Home Assistant Operating System: 16.2
• Integration version: 2.10.0

I saw that this issue was flagged as fixed, but it’s still occurring for me after fully updating and restarting Home Assistant.

Please let me know if you’d like me to share logs, screenshots, or any other info to help debug.

Thanks for your work on this integration!

**Comment by nzjjay** [comment]
Hi All, I can also confirm I am still experiencing this issue for Auckland, NZ

**Comment by MottledBadger** [comment]
I had the same problem, but just repaired mine. You will need to update all the code for the Auckland source file from here: https://github.com/mampfes/hacs_waste_collection_schedule/blob/dedf9f537539f69e9664ed22bf53f72c3579c1e6/custom_components/waste_collection_schedule/waste_collection_schedule/source/aucklandcouncil_govt_nz.py

**Comment by PHamiltonNZ** [comment]
Thanks, can you please provide instructions for how to repair? I pasted the code into the source file but when I try to add the integration with my area number, I get this error
The source returned an invalid response: "'NoneType' object has no attribute 'find_all'". Please check the provided arguments and try again.

**Comment by scaryfish** [comment]
> Thanks, can you please provide instructions for how to repair? I pasted the code into the source file but when I try to add the integration with my area number, I get this error The source returned an invalid response: "'NoneType' object has no attribute 'find_all'". Please check the provided arguments and try again.

Same here. Using a fresh install of Waste Collection Schedule gives the above error, and replacing /homeassistant/custom_components/waste_collection_schedule/waste_collection_schedule/source/aucklandcouncil_govt_nz.py with the above modified file still gives the same error.

**Comment by Alfiegerner** [comment]
My fix hasn't been merged yet, you'll need to use the file from the pull request linked above.

**Comment by SerhioDuras** [comment]
> Thanks, can you please provide instructions for how to repair? 

You should update config file for Auckland. Just follow the next steps:

1. Install **File editor** via **Settings -> Add-ons** 
2. Start the service **File editor** by **Start** button
3. When the service is started, click **Open Web UI** button (right side) in the same window
4. Click **Browse Filesystem** button (folder icon) and follow the next direction:

/homeassistant/custom_components/waste_collection_schedule/waste_collection_schedule/source/aucklandcouncil_govt_nz.py

5. Go to the link provided by @MottledBadger and copy whole code and replace everything in **aucklandcouncil_govt_nz.py** config file. Save the file.
6. Restart HA
7. Reconfig **Waste collection schedule**.

**Comment by PHamiltonNZ** [comment]
That's great, thank you

**Comment by brightsparkzn** [comment]
Thank you for the step by step. Have a functioning feed again. One oddity though, it its returning two rubbish and recycling attributes on the same date. Is anyone else experiencing this?

**Comment by PHamiltonNZ** [comment]
> Thank you for the step by step. Have a functioning feed again. One oddity though, it its returning two rubbish and recycling attributes on the same date. Is anyone else experiencing this?

Yes, I get the double up as well

**Comment by kellyatkinson** [comment]
I spotted this PR which fixes the duplicates: https://github.com/mampfes/hacs_waste_collection_schedule/pull/4842

**Comment by nzjjay** [comment]
If anyone wants an Auckland specific setup and doesn't want to edit their current waste_collection config files, I have created a custom integration here: https://github.com/nzjjay/auckland_waste, can add via HACS Custom Integrations.

**Comment by 5ila5** [comment]
Should be fixed by #4823


This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA
Do "update" of WCS until the next release, as pressing the update button performs a "downgrade" to the latest release version

**Comment by zdev-code** [comment]
Food and recycling sensors say unknown for me

**Comment by kellyatkinson** [comment]
Please check the names of your sensors. I had to adjust “recycle” to
“recycling” in the last few days to get mine to work again.
