### ISSUE TITLE
[Bug]: UK Swale council no longer working

### ISSUE THREAD

**Issue by dolce08** [mampfes/hacs_waste_collection_schedule#4996]
### I Have A Problem With:

A specific source

### What's Your Problem

UK swale council no longer works. I tried a re-adding it and receive the error:
The source returned an invalid response: "'NoneType' object has no attribute 'find_all'". Please check the provided arguments and try again.

Before I removed the integration the log was showing an error relating to line 96 of swale_gov_uk.py

### Source (if relevant)

swale_gov_uk

### Logs

```Shell

```

### Relevant Configuration

```YAML

```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by AKWillows** [comment]
Have the same issue with Swale.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 7 December 2025 at 15:21:30 (4 occurrences)
Last logged: 18:16:52

fetch failed for source Swale Borough Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/swale_gov_uk.py", line 96, in fetch waste_items = waste_list.find_all("li") ^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by dolce08** [comment]
Fixed by updating the headers in swale_gov_uk.py

`headers = {
            # latest chrome UA
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36',
        }`

**Comment by AKWillows** [comment]
Hi @dolce08 

I tried updating the headers in the .py section using your suggestion but all of the entities are still showing as Unavailable after a reload of the integration. Did I do something wrong?

<img width="1254" height="221" alt="Image" src="https://github.com/user-attachments/assets/f795f426-e7f5-429d-89c5-27df83105ba7" />

**Comment by AKWillows** [comment]
I am seeing this error after updating the headers as you suggest @dolce08 

<img width="999" height="374" alt="Image" src="https://github.com/user-attachments/assets/b295230f-db68-4541-a9fa-b5e44d227c58" />
