### ISSUE TITLE
[Bug]: umweltverbaende_at stopped working

### ISSUE THREAD

**Issue by mindestens** [mampfes/hacs_waste_collection_schedule#5100]
### I Have A Problem With:

A specific source

### What's Your Problem

After HA restart the attached error occurs. Therefore the integration is broken.

Thank you!

### Source (if relevant)

umweltverbaende_at

### Logs

```Shell
Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule (Dokumentation)

fetch failed for source Die NÖ Umweltverbände: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/umweltverbaende_at.py", line 490, in fetch return self.fetch_new() ~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/umweltverbaende_at.py", line 697, in fetch_new bin_type = zone["fraktion"] ~~~~^^^^^^^^^^^^ TypeError: string indices must be integers, not 'str'
```

### Relevant Configuration

```YAML
https://stpoeltenland.umweltverbaende.at/fuer-die-bevoelkerung/abholtermine/#

waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "stpoeltenland"
        municipal: "-REMOVED-"
        town: "-REMOVED-"
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by mindestens** [comment]
I was able to fix the issue (at least) for the **GVU St. Pölten** region.

This is a **local workaround**, not an official patch.

**Changes (excerpt)**

```
# Change 1: Bug fix in get_genereic() - Line 577
560:    def get_genereic(
561:        self,
562:        s: requests.Session,
563:        data: dict[str, str],
564:        arg_name: str,
565:        arg_value: str | None,
566:        element_name: str,
567:        newxt_stage,
568:    ) -> dict[str, str]:
...
575:        # Handle API errors
576:        if options_html == "error":
577:            return newxt_stage(s, data)  # ← FIXED: was self.get_hnr(s, data) before
578:
579:        # No dropdown for this element

......

# Change 2: Dynamic year handling - Lines 735-744
735:        # Determine which years to fetch (current and/or next year)
736:        now = datetime.now()
737:        current_year = now.year
738:        next_year = now.year + 1
739:        
740:        # In December, prioritize next year but also fetch current year
741:        years_to_try = [next_year, current_year] if now.month == 12 else [current_year, next_year]
742:
743:        all_entries: list[Collection] = []
744:
745:        # Try to fetch data for both years
746:        for jahr in years_to_try:  # ← NEW: Loop over both years

......

# Change 3: Added year parameter - Lines 747-751
747:            initial_data = {
748:                "nonce": nonce,
749:                "search[gemeinde]": mun_value,
750:                "jahr": str(jahr),  # ← NEW: Year parameter added
751:            }

......

# Change 4: Direct zone fetching with year - Lines 765-779
765:            # Try to get zones directly (works for most municipalities)
766:            zones_data = {
767:                "action": "get_zone_and_abfuhrtermine",  # ← NEW: Direct call
768:                "nonce": nonce,
769:                "element": "",
770:                "jahr": str(jahr),  # ← NEW: Year parameter
771:            }
772:
773:            # Copy all search parameters
774:            for key, value in data.items():
775:                if key.startswith("search["):
776:                    zones_data[key] = value
777:
778:            r_zones = s.post(f"{self._district_url}wp-admin/admin-ajax.php", data=zones_data)
779:            r_zones.raise_for_status()

......

# Change 5: Type checking for zones - Lines 782-818
782:            # Process zones if successful
783:            if zones_response.get("success"):
784:                zones = zones_response.get("zones", [])
785:
786:                if isinstance(zones, list) and len(zones) > 0:
787:                    for zone in zones:
788:                        if not isinstance(zone, dict):  # ← NEW: Type check added
789:                            continue
790:
791:                        bin_type = zone.get("fraktion")
792:                        if not bin_type:
793:                            continue
794:
795:                        dates = zone.get("dates", [])
796:                        if not isinstance(dates, list):
797:                            continue
798:
799:                        for date_dict in dates:
800:                            if not isinstance(date_dict, dict):
801:                                continue
802:
803:                            date_str = date_dict.get("date")
804:                            if not date_str:
805:                                continue
806:
807:                            try:
808:                                date_ = datetime.strptime(date_str, "%Y-%m-%d").date()
809:                                all_entries.append(  # ← NEW: Collects all entries
810:                                    Collection(
811:                                        date=date_,
812:                                        t=bin_type,
813:                                        icon=self.get_icon(bin_type),
814:                                    )
815:                                )
816:                            except ValueError:
817:                                continue
818:

......

# Change 6: Return after both years - Lines 819-821
819:        # Return all collected entries
820:        if all_entries:  # ← NEW: Returns all collected dates
821:            return all_entries

......

# Change 7: Fallback with year parameter - Lines 823-828
823:        # If direct zone request didn't work, fall back to fraktionen method
824:        fraktionen_data = {
825:            "nonce": nonce,
826:            "action": "get_fraktionen",
827:            "element": "",
828:            "jahr": str(current_year),  # ← NEW: Year parameter in fallback too
829:        }
......
```
### [Complete file](https://github.com/user-attachments/files/24218394/umweltverbaende_at.py)

- Replace the file manually in `custom_components/waste_collection_schedule/waste_collection_schedule/source` (I recommend creating a backup of your existing file first, for example: => `cp umweltverbaende_at.py umweltverbaende_at.py.bck`
- Then restart your HA instance.

**Comment by 5ila5** [comment]
fixed by #5135 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA
Do not  "update" WCS through HACS until the next release, as pressing the update button performs a "downgrade" to the latest release version

**Comment by traktuner** [comment]
@mindestens Unfortunately I still get an error for „GVA Tulln“:
Die Quelle hat eine leere Antwort zurückgegeben. Bitte überprüfe die Argumente und versuche es erneut.

**Comment by mindestens** [comment]
@traktuner Yes, this is why I mentioned "..**at least for the GVU St. Pölten region**"
Unfortunately, GVU Tulln doesn't provide ICA or API sources anymore: https://gvatulln.at/fuer-die-bevoelkerung/abholtermine
So this is not related with this Bug / PR
