### ISSUE TITLE
[Bug]: Not able to configure for Hume

### ISSUE THREAD

**Issue by TehStoneMan** [mampfes/hacs_waste_collection_schedule#5180]
### I Have A Problem With:

A specific source

### What's Your Problem

Has been working fine until recently. Have tried configuring manually (YAML) and through GUI.

### Source (if relevant)

hume_vic_gov_au

### Logs

```Shell
GUI error:
The source returned an invalid response: "Expecting value: line 1 column 1 (char 0)". Please check the provided arguments and try again.

----
Logs:
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 6:43:54 PM (1 occurrence)
Last logged: 6:43:54 PM

fetch failed for source Hume City Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/hume_vic_gov_au.py", line 70, in fetch data = json.loads(r.text) File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads return _default_decoder.decode(s) ~~~~~~~~~~~~~~~~~~~~~~~^^^ File "/usr/local/lib/python3.13/json/decoder.py", line 345, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/json/decoder.py", line 363, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: hume_vic_gov_au
      args:
        address: "19 Potter Street Craigieburn 3064" #"<Real address removed>"
        predict: true
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by epajfl00** [comment]
I too had this same issue (no longer working) for Hume, so I simply reverted back to version 2.10 and all good for now.
So there is definitely a problem with the last update of 2.11.

**Comment by tamimology** [comment]
Same for me, and I thought I had done something wrong 😅

**Comment by mallyz** [comment]
I was having the exact same issue, reverted back to 2.10 once I seen this thread! Thanks!! 

Definitely an issue with how 2.11 completely changes the to the new website API, seems that the Hume website doesn't allow access to scrape the site.

**Comment by bym007** [comment]
I had the same issue for a few weeks, and finally got a chance to check it today. It seems the API has changed, which has broken this integration. I had to rollback to 2.10 which fixed the issue for now, but happy to provide assistance or logs to devs, to troubleshoot this issue.

**Comment by dt215git** [comment]
The 2.11.0 script is failing in HA because the website returns a `403 Access Denied` html message and the script is expecting a json response, hence the `JSONDecodeError`. This is happening on the first request where it's using the address to try and get the location_id needed to subsequently retrieve the schedule.

The test cases work fine from a dev environment so it doesn't appear to be an issue with the latest script per-se. It may be related to something missing/extra in the headers HA supplies with the request.

```bash
Testing source hume_vic_gov_au ...
  found 8 entries for 19 Potter
    2026-01-22 : Garbage [mdi:trash-can]
    2026-01-29 : Garbage [mdi:trash-can]
    2026-02-05 : Garbage [mdi:trash-can]
    2026-02-12 : Garbage [mdi:trash-can]
    2026-01-22 : Recycling [mdi:recycle]
    2026-02-05 : Recycling [mdi:recycle]
    2026-01-29 : Food and garden [mdi:leaf]
    2026-02-12 : Food and garden [mdi:leaf]
  found 3 entries for 1/90 Vineyard
    2026-01-21 : Garbage [mdi:trash-can]
    2026-01-21 : Recycling [mdi:recycle]
    2026-01-28 : Food and garden [mdi:leaf]
  found 3 entries for 9-19 McEwen
    2026-01-21 : Garbage [mdi:trash-can]
    2026-01-28 : Recycling [mdi:recycle]
    2026-01-21 : Food and garden [mdi:leaf]
  found 3 entries for 33 Toyon
    2026-01-23 : Garbage [mdi:trash-can]
    2026-01-30 : Recycling [mdi:recycle]
    2026-01-23 : Food and garden [mdi:leaf]
```

**Comment by seedzero** [comment]
Fixed in #5449

**Comment by jeffles89** [comment]
still cant configure in 2.11
when putting in address as per the mentioned instructions from know my bin day it returns this error 

The source returned an invalid response:
"Expecting value : line 1 column 1 (char 0)". Please Check the provided arguments and try again

**Comment by seedzero** [comment]
@jeffles89 yes, this will continue to be broken until the next release, the fix is ready but hasn't been merged. Either roll back to the previous version, or wait for the fix

**Comment by jeffles89** [comment]
> [@jeffles89](https://github.com/jeffles89) yes, this will continue to be broken until the next release, the fix is ready but hasn't been merged. Either roll back to the previous version, or wait for the fix

oh ok cheers
ill roll back for time being

curious do we have an eta on when it will be released

**Comment by dt215git** [comment]
Alternatively, cut and paste the 2 new lines into the `hume_vic_gov_au.py` file on your local HA instance, and do a reboot.
You can see the changes if you look at the [Files changed](https://github.com/mampfes/hacs_waste_collection_schedule/pull/5449/changes) tab in the PR.

If you check the release notes when the next release is pushed out and you see Hume listed, your local edit will get overwritten with the accepted version when you upgrade - but you'll not notice any difference.

If Hume isn't listed and you install the new release, it'll overwrite you local file with the original, non-working, script.

**Comment by HallyAus** [comment]
This one is long since fixed and shipped — it just never got closed.

@seedzero's fix (#5449) was merged on 9 Feb, and the first release after that was **2.12.0 (1 Apr)**, so it has been in every release since, up to the current v2.32.0. The source was hardened again afterwards: cloudscraper was replaced with curl_cffi Chrome impersonation (2 Apr), and it moved onto the shared OpenCities client in #6960 (19 Jul).

Verified live just now on `master`, including the exact config from the report (`19 Potter Street Craigieburn 3064` with `predict: true`):

```
test_sources.py -s hume_vic_gov_au -l
  found 8 entries for 19 Potter      2026-09-17 Garbage, 2026-09-17 Recycling, 2026-09-24 Food and garden, ...
  found 3 entries for 1/90 Vineyard  (1/90 Vineyard Road Sunbury, VIC 3429)
  found 3 entries for 9-19 McEwen    (9-19 MCEWEN DRIVE SUNBURY VICTORIA 3429)
  found 3 entries for 33 Toyon       (33 TOYON ROAD KALKALLO 3064)
```

For the record, @dt215git's diagnosis back in January was exactly right — the `JSONDecodeError` was a `403 Access Denied` HTML page being parsed as JSON, which is why the dev environment worked while Home Assistant didn't. That's still the failure mode if the impersonation is bypassed: plain `requests` to Hume's search endpoint returns a 403 Akamai page from here today.

Anyone still on 2.10 can safely upgrade. @mampfes this looks closeable (fixed by #5449, released in 2.12.0) — your call. No PR needed.

**Comment by bbr111** [comment]
Thanks everyone for the reports and the diagnosis.

This was fixed in #5449, merged on 9 Feb and first released in 2.12.0. The source has since been hardened further. It now uses curl_cffi Chrome impersonation, which avoids the 403 Akamai page that was being parsed as JSON, and it runs on the shared OpenCities client. Anyone still on 2.10 can safely upgrade to the latest release.

If you still see this error on the current version, please open a new issue with fresh logs. Closing as fixed.
